#!/bin/bash

# 🚀 Production Deployment Script for AURA Platform
# This script handles the complete deployment process to production

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✅${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠️${NC} $1"
}

log_error() {
    echo -e "${RED}❌${NC} $1"
}

log_step() {
    echo -e "${BOLD}${BLUE}🔄${NC} $1"
}

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    log_error "package.json not found. Please run this script from the backend directory."
    exit 1
fi

log_step "Starting AURA Platform Production Deployment"

# Step 1: Environment Check
log_step "Checking environment configuration..."

if [ ! -f ".env" ]; then
    log_error ".env file not found. Please create it with your Supabase credentials."
    exit 1
fi

# Check required environment variables
required_vars=("DATABASE_URL" "SUPABASE_URL" "SUPABASE_ANON_KEY" "JWT_SECRET")
for var in "${required_vars[@]}"; do
    if ! grep -q "^${var}=" .env; then
        log_error "Missing required environment variable: $var"
        exit 1
    fi
done

log_success "Environment configuration verified"

# Step 2: Install Dependencies
log_step "Installing dependencies..."
npm ci --production
log_success "Dependencies installed"

# Step 3: Build the Application
log_step "Building the application..."
npm run build
log_success "Application built successfully"

# Step 4: Database Migration
log_step "Running database migrations..."

# Check if Prisma is available
if ! command -v npx &> /dev/null; then
    log_error "npx not found. Please install Node.js and npm."
    exit 1
fi

# Generate Prisma client
log_info "Generating Prisma client..."
npx prisma generate

# Push schema to database
log_info "Pushing schema to database..."
npx prisma db push

# Run seed if needed
if [ -f "prisma/seed.ts" ]; then
    log_info "Running database seed..."
    npx prisma db seed
fi

log_success "Database migration completed"

# Step 5: Test Database Connection
log_step "Testing database connection..."
if npx prisma db pull > /dev/null 2>&1; then
    log_success "Database connection verified"
else
    log_error "Database connection failed. Please check your DATABASE_URL."
    exit 1
fi

# Step 6: Security Check
log_step "Running security checks..."

# Check for common security issues
if grep -q "password.*=" .env; then
    log_warning "Found password in .env file. Ensure this is not committed to version control."
fi

if grep -q "secret.*=" .env; then
    log_warning "Found secret in .env file. Ensure this is not committed to version control."
fi

log_success "Security checks completed"

# Step 7: Performance Check
log_step "Running performance checks..."

# Check if the application starts without errors
log_info "Testing application startup..."
timeout 10s npm start > /dev/null 2>&1 || {
    log_error "Application failed to start. Please check the logs."
    exit 1
}

log_success "Performance checks completed"

# Step 8: Generate Deployment Report
log_step "Generating deployment report..."

cat > deployment-report.md << EOF
# 🚀 AURA Platform Deployment Report

## Deployment Information
- **Timestamp**: $(date)
- **Node Version**: $(node --version)
- **NPM Version**: $(npm --version)
- **Environment**: Production

## Database Configuration
- **Database**: Supabase PostgreSQL
- **Connection**: Verified
- **Schema**: Up to date

## Application Status
- **Build**: Successful
- **Dependencies**: Installed
- **Database**: Migrated
- **Security**: Checked

## Next Steps
1. Deploy to your hosting platform (Vercel, Railway, etc.)
2. Set environment variables in your hosting platform
3. Test all API endpoints
4. Monitor application performance
5. Set up monitoring and logging

## Environment Variables Required
\`\`\`
DATABASE_URL=postgresql://postgres:[PASSWORD]@db.[PROJECT-REF].supabase.co:5432/postgres
SUPABASE_URL=https://your-project-id.supabase.co
SUPABASE_ANON_KEY=your-anon-key
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key
JWT_SECRET=your-jwt-secret
NODE_ENV=production
PORT=5000
\`\`\`

## API Endpoints to Test
- GET /api/health
- POST /api/auth/register
- POST /api/auth/login
- GET /api/users
- POST /api/posts
- POST /api/likes/like

## Monitoring
- Check Supabase dashboard for database performance
- Monitor application logs
- Set up error tracking
- Configure backups

---
Generated by AURA Platform Deployment Script
EOF

log_success "Deployment report generated: deployment-report.md"

# Step 9: Final Verification
log_step "Running final verification..."

# Check if all critical files exist
critical_files=("dist/server.js" "package.json" "prisma/schema.prisma")
for file in "${critical_files[@]}"; do
    if [ ! -f "$file" ]; then
        log_error "Critical file missing: $file"
        exit 1
    fi
done

log_success "Final verification completed"

# Step 10: Deployment Instructions
log_step "Deployment Instructions"

echo ""
echo -e "${BOLD}${GREEN}🎉 Deployment Preparation Complete!${NC}"
echo ""
echo -e "${BOLD}Next Steps:${NC}"
echo "1. Deploy to your hosting platform (Vercel, Railway, Heroku, etc.)"
echo "2. Set the following environment variables in your hosting platform:"
echo ""
echo -e "${YELLOW}Required Environment Variables:${NC}"
echo "DATABASE_URL=postgresql://postgres:[PASSWORD]@db.[PROJECT-REF].supabase.co:5432/postgres"
echo "SUPABASE_URL=https://your-project-id.supabase.co"
echo "SUPABASE_ANON_KEY=your-anon-key"
echo "SUPABASE_SERVICE_ROLE_KEY=your-service-role-key"
echo "JWT_SECRET=your-jwt-secret"
echo "NODE_ENV=production"
echo "PORT=5000"
echo ""
echo -e "${YELLOW}Optional Environment Variables:${NC}"
echo "CLOUDINARY_CLOUD_NAME=your-cloud-name"
echo "CLOUDINARY_API_KEY=your-api-key"
echo "CLOUDINARY_API_SECRET=your-api-secret"
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_PORT=587"
echo "SMTP_USER=your-email@gmail.com"
echo "SMTP_PASS=your-app-password"
echo "FRONTEND_URL=https://your-domain.com"
echo ""
echo -e "${BOLD}Testing Commands:${NC}"
echo "curl https://your-api-domain.com/api/health"
echo "curl -X POST https://your-api-domain.com/api/auth/register -H 'Content-Type: application/json' -d '{\"email\":\"test@example.com\",\"password\":\"password123\"}'"
echo ""
echo -e "${BOLD}Monitoring:${NC}"
echo "- Check Supabase dashboard for database performance"
echo "- Monitor application logs in your hosting platform"
echo "- Set up error tracking (Sentry, etc.)"
echo "- Configure automated backups"
echo ""

log_success "Deployment preparation completed successfully!"
